spring:
  application:
    name: Day7

logging:
  level:
    root: INFO
    com.example.Day7: DEBUG

  file:
    name: logs/app.log

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %level - %logger{36} - %msg%n"

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
      clean-history-on-start: true
